#+TITLE: External examining -- what and why
#+AUTHOR: Guy McCusker
#+DATE: CSEG , September 2026 

#+include: "./lecture-preamble-light.org"

* The role of External Examiner

#+ATTR_REVEAL: :frag (appear)
 - A network of QA between universities which autonomously award degrees
 - Overseeing quality and standards

** What it involves

#+ATTR_REVEAL: :frag (appear)
 - Appointments for 2 -- 4 years to oversee one or more degree programmes
 - QA and feedback on assessments throughout the year
 - Review of marking and QA processes
 - Attendance at exam boards to oversee process
 - Discussion with students
 - Writing an annual report

** In the old days...

Pre-pandemic, a great deal of the work was done in person.

#+ATTR_REVEAL: :frag (appear)
Typically visit the university two or three times in the year:
#+ATTR_REVEAL: :frag (appear)
 - reviewing exam papers and a selection of coursework assignments
 - reviewing marking of exams and projects
 - attending exam board
#+ATTR_REVEAL: :frag (appear)
On at least one of these occasions there would be a meeting with students.

** In today's world


#+ATTR_REVEAL: :frag (appear)
 - You'll be given access to Moodle or equivalent and expected to review everything
 - This is not practical!
 - So pick and choose. Remember that in the past it was all done in a few days.
 - Seek guidance from the relevant Director of Teaching or equivalent


#+ATTR_REVEAL: :frag (appear)
Around one week of work seems a reasonable estimate.

** A look at the form

- Please comment on whether the standards set by the University are, in your view, appropriate for the qualification being studied.

- Please comment on the appropriateness of the published marking criteria.

- Please comment on whether you believe standards of student performance and achievement are comparable to those of similar courses in other higher education institutions?

- Please comment on whether you believe existing assessment processes measure student achievement rigorously and fairly against the intended course and module learning outcomes.

#+reveal:split

- On the basis of the sample of assessments that you have reviewed, please comment on the appropriateness of the application of the marking and moderation processes as evidenced by the annotated scripts and marks and feedback given.

- Please indicate whether you are satisfied that the processes for assessment, examination and the determination of awards have been sound, appropriate and fairly conducted.

- Do you have any comments on resources as they impact on student performance in assessment processes?

- Please comment on any good practice that you have observed related to teaching, learning and assessment
#+reveal:split  

- Please comment on the quality of teaching and learning methods and learning opportunities (based on the standard set of materials sent, not observation of teaching or access to teaching resources).

- Have you had sufficient access to and the power to call upon any materials needed to make the required judgements? If not, please give details.

* Am I qualified to do this?

If you've taught a course and attended an exam board, then yes!

#+ATTR_REVEAL: :frag (appear)
 - Focus on /process/ over content where you don't know the topics in detail
   - are the setting, checking and marking processes appropriate?
   - are they being followed?
   - what happens when something goes wrong?
 - Sometimes you'll spot obvious things:
   - assignments solvable by AI
   - 90% of students scoring 80% or more on a unit, or everyone failing
   - project double-marking not being done in good faith
 - And you do have subject expertise!

* Why would I do this?

#+ATTR_REVEAL: :frag (appear)
 - Helping out a friend's department and the sector
 - Seeing how other universities work is interesting and can be useful
 - Sharing ideas
 - Growing your academic network
 - Marker of esteem 
 - [and they pay you]




   


 
     














